---
- hosts: tomcatServers
  vars:
    #war_url: http://172.31.37.250:8081/repository/maven-snapshots/com/maven/SimpleWebApplication'/1.0.0-SNAPSHOT/SimpleWebApplication'-1.0.0-20241018.135913-1.war
    metadata_url: "http://13.126.68.188:8081/repository/maven-snapshots/com/maven/SimpleWebApplication/1.0.0-SNAPSHOT/maven-metadata.xml"
    app_url: "http://13.126.68.188:8081/repository/maven-snapshots/com/maven/SimpleWebApplication/1.0.0-SNAPSHOT/SimpleWebApplication-{{ latest_artifact_version }}.war"
    nexus_username: "admin"
    nexus_password: "admin"
  become_user: tomcat1
  become: true
  roles:
    - stopTomcat
    - takeBackup
    - downloadwar
    - startTomcat
